### ISSUE TITLE
Minor mistake in README, line 93

### ISSUE THREAD

**Issue by sargalias** [Connormiha/bem-css-modules#1]
In the `README.MD` file, line 93
`const b = (style);// Create BEM Generator for current CSS module`
should be
`const b = block(style);// Create BEM Generator for current CSS module`

It's extremely minor. Also I'm happy to make the change if you'd like.

P.S. Absolutely LOVE this repository. It is 100% essential. Very. good. work.

**Comment by Connormiha** [comment]
Thanks for good words @sargalias 
I updated readme.
